[build]
  base = "src/frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  ESBUILD_TMPDIR = "/tmp"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
